data:
  corpus:                                 
    name: 'Librispeech'                   # Specify corpus
    path: 'save/aug_20dB'          # Path to raw LibriSpeech dataset
    dev_split: ['dev-clean']              # Name of data splits to be used as validation set
    test_split: ['test-clean']              # Name of data splits to be used as validation set
    bucketing: True                       # Enable/Disable bucketing 
    batch_size: 12
    in_memory: False
  audio:
    num_freq: 1025
    num_mels: 80
    frame_length_ms: 50
    frame_shift_ms: 12.5
    preemphasis_coeff: 0.97
    sample_rate: 16000
    use_linear: False                      ### Return Linear spectrogram
    snr_range: [-1]
    time_stretch_range: [1.0, 1.0]
    inverse_prob: 0.0
decode:
  beam_size: 1
src:
