data:
  corpus:                                 
    name: 'Librispeech'                   # Specify corpus
    path: 'save/LibriSpeech'          # Path to raw LibriSpeech dataset
    train_split: ['train-clean-100']      # Name of data splits to be used as training set
    dev_split: ['dev-clean']              # Name of data splits to be used as validation set
    bucketing: True                       # Enable/Disable bucketing 
    batch_size: 24
  audio:
    num_freq: 1025
    num_mels: 80
    frame_length_ms: 50
    frame_shift_ms: 12.5
    preemphasis_coeff: 0.97
    sample_rate: 16000
    use_linear: False                      ### Return Linear spectrogram
    # augmentation
    snr_range: [10, 100]
    time_stretch_range: [0.9, 1.1]
    inverse_prob: 0.0
  text:
    mode: 'subword'                       # 'character'/'word'/'subword'
    vocab_file: 'tests/sample_data/subword.model'

hparas:                                   # Experiment hyper-parameters
  valid_step: 5000
  curriculum: 0
  max_step: 350001
  tf_start: 1.0
  tf_end: 0.0
  tf_step: 500000
  optimizer: 'SGD'
  nesterov: True
  momentum: 0.9
  lr: 0.01
  lr_scheduler: 'fixed'                   # 'fixed'/'warmup'/'decay'
  
model:                                    # Model architecture
  ctc_weight: 1.0                         # Weight for CTC loss
  delta: 2
  encoder:
    cnn:
      type: 'vgg'                             # 4x reduction on time feature extraction
    module: 'LSTM'                        # 'LSTM'/'GRU'/'Transformer'
    bidirection: True
    dim: [320,320,320,320,320]
    dropout: [0,0,0,0,0]
    layer_norm: [False,False,False,False,False]
    proj: [True,True,True,True,True]      # Linear projection + Tanh after each rnn layer
    sample_rate: [1,1,1,1,1]
    sample_style: 'drop'                  # 'drop'/'concat'
  attention:
    mode: 'loc'                           # 'dot'/'loc'
    dim: 300
    num_head: 1
    v_proj: False                         # if False and num_head>1, encoder state will be duplicated for each head
    temperature: 1                        # scaling factor for attention
    loc_kernel_size: 100                  # just for mode=='loc'
    loc_kernel_num: 10                    # just for mode=='loc'
  decoder:
    module: 'LSTM'                        # 'LSTM'/'GRU'/'Transformer'
    dim: 320
    layer: 1
    dropout: 0
    #layer_norm: False
